spring:
  application:
    name: tcc-order
  thymeleaf:
    prefix: classpath:/templates
    suffix: .ftl
    mode: HTML5
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://localhost:3306/tcc_ord
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9091
mybatis:
  type-aliases-package: com.chz.entity
  mapper-locations: classpath*:mapper/**/*.xml